version: 2
jobs:
  build:
    docker:
    
    steps:
      - checkout
      
      - run: yarn install

  
      - run: docker info
      - run: docker build --rm=false -t restful-node8:1.0 .

      - test:
        override:
          - docker run -d -p 9200:9200 circleci/elasticsearch; sleep 10
          - curl --retry 10 --retry-delay 5 -v http://localhost:9200

      - run:
          name: Docker Image Build
          command: |
            docker build -t restful-node8:1.0 .