version: 2
jobs:
  build:
    
    steps:
      - checkout
      
      - run: yarn install
      - run: docker info
  
      - run:
          name: Docker Image Build
          command: |
            docker build -t restful-node8:1.0 .