version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    
    steps:
      - checkout
      - run: yarn install
      - run : yarn test
      - run:
          name: Docker Image Build
          command: |
            docker build -t restful-node8:1.0 .